// файл actions/actionTypes.js
// Search
export const SEARCH_ITEMS_REQUEST='SEARCH_ITEMS_REQUEST';
export const SEARCH_ITEMS_FAILURE='SEARCH_ITEMS_FAILURE';
export const SEARCH_ITEMS_SUCCESS='SEARCH_ITEMS_SUCCESS';
export const CHANGE_SEARCH_FIELD='CHANGE_SEARCH_FIELD';
export const CHANGE_CATEGORY='CHANGE_CATEGORY';
export const CHANGE_OFFSET='CHANGE_OFFSET';

// Cart
export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_PURCHASE_ITEMS = 'CART_PURCHASE_ITEMS';
export const CART_PURCHASE_SUCCESS = 'CART_PURCHASE_SUCCESS';
export const CART_PURCHASE_FAILURE = 'CART_PURCHASE_FAILURE';

// Alerts
export const START_ALERT_MESSAGE = 'START_ALERT_MESSAGE';

// Products
export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST';
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const SET_ITEMS_REQUEST = 'SET_ITEMS_REQUEST';

// Categories
export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';
